# Generated by Django 3.1.7 on 2021-04-20 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BanTin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TimeCreate', models.DateTimeField(auto_now=True)),
                ('NoiDung', models.CharField(default='', max_length=5000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ThongTinCaNhan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IDNguoiDung', models.CharField(max_length=20)),
                ('HoTen', models.CharField(max_length=80)),
                ('NgaySinh', models.DateField(verbose_name='Ngay Sinh')),
                ('SDT', models.CharField(default=0, max_length=15, null=True)),
                ('DiaChi', models.CharField(default='', max_length=80, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BinhLuan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NguoiBinhLuan', models.CharField(max_length=80)),
                ('NoiDungBinhLuan', models.CharField(max_length=5000)),
                ('IDBinhLuan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TrangCaNhan.bantin')),
            ],
        ),
        migrations.AddField(
            model_name='bantin',
            name='IDBanTin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TrangCaNhan.thongtincanhan'),
        ),
    ]
