# Generated by Django 3.1.7 on 2021-04-22 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TrangCaNhan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bantin',
            name='TenNguoiPost',
        ),
    ]
