# Generated by Django 3.1.7 on 2021-04-20 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrangCaNhan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thongtincanhan',
            name='GioiTinh',
            field=models.TextField(choices=[('Nam', 'Nam'), ('Nu', 'Nu')], default='', max_length=5),
        ),
    ]
