# Generated by Django 3.1.7 on 2021-04-20 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrangCaNhan', '0002_thongtincanhan_gioitinh'),
    ]

    operations = [
        migrations.AddField(
            model_name='bantin',
            name='TenNguoiPost',
            field=models.CharField(default='', max_length=80),
        ),
    ]
