# Generated by Django 3.1.7 on 2021-04-22 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrangCaNhan', '0002_remove_bantin_tennguoipost'),
    ]

    operations = [
        migrations.AddField(
            model_name='bantin',
            name='TenNguoiPost',
            field=models.CharField(default='', max_length=20, null=True),
        ),
    ]
