# Generated by Django 3.1.7 on 2021-04-22 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrangCaNhan', '0003_bantin_tennguoipost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bantin',
            name='TenNguoiPost',
            field=models.CharField(default=' ', max_length=20, null=True),
        ),
    ]
