# Generated by Django 3.1.7 on 2021-04-20 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrangCaNhan', '0003_bantin_tennguoipost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thongtincanhan',
            name='GioiTinh',
            field=models.TextField(choices=[('Male', 'Nam'), ('Female', 'Nu')], default='', max_length=6),
        ),
    ]
