# Generated by Django 3.1.7 on 2021-04-22 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrangCaNhan', '0004_auto_20210422_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bantin',
            name='TenNguoiPost',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
