# Generated by Django 3.1.7 on 2021-04-20 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrangCaNhan', '0005_auto_20210420_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bantin',
            name='TenNguoiPost',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
