# Generated by Django 3.1.7 on 2021-04-21 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrangCaNhan', '0006_auto_20210420_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='thongtincanhan',
            name='TimeCreate',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='thongtincanhan',
            name='GioiTinh',
            field=models.TextField(choices=[('Nam', 'Nam'), ('Nu', 'Nu')], default='', max_length=6),
        ),
    ]
