# Generated by Django 3.1.7 on 2021-04-21 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrangCaNhan', '0007_auto_20210421_0424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bantin',
            name='IDBanTin',
            field=models.CharField(max_length=20),
        ),
    ]
