# Generated by Django 3.1.7 on 2021-04-22 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrangCaNhan', '0008_auto_20210421_0829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bantin',
            name='TenNguoiPost',
        ),
        migrations.AddField(
            model_name='bantin',
            name='TenNguoiPost',
            field=models.ManyToManyField(to='TrangCaNhan.ThongTinCaNhan'),
        ),
    ]
